# Generated by Django 3.0.4 on 2020-03-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='static/img/static-user.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
