# Generated by Django 2.2.5 on 2019-09-16 12:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('date_added', models.DateField(blank=True, default=datetime.datetime.now)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('primary_subtitle', models.CharField(blank=True, max_length=200)),
                ('secondary_subtitle', models.CharField(blank=True, max_length=200)),
                ('added_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
