# Generated by Django 3.0.2 on 2020-04-12 09:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField(null=True)),
                ('link', models.CharField(max_length=200)),
                ('date_added', models.DateField(blank=True, default=datetime.datetime.now)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('primary_subtitle', models.CharField(blank=True, max_length=200)),
                ('secondary_subtitle', models.CharField(blank=True, max_length=200)),
                ('for_parents', models.BooleanField(default=False)),
                ('watched', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(to='torrents.Genre')),
            ],
        ),
    ]
