# Generated by Django 3.0.4 on 2020-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='for_parents',
            field=models.BooleanField(default=False),
        ),
    ]
