# Generated by Django 3.0.2 on 2020-04-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
