# Generated by Django 3.0.2 on 2020-04-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0002_auto_20200412_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
