# Generated by Django 3.0.4 on 2020-03-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0002_torrent_for_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='for_parents',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
