# Generated by Django 3.0.4 on 2020-04-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0003_auto_20200412_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
