# Generated by Django 3.0.4 on 2020-03-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0004_auto_20200327_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='torrent',
            name='genres',
            field=models.ManyToManyField(to='torrents.Genre'),
        ),
    ]
