# Generated by Django 3.0.2 on 2020-04-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0007_auto_20200330_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
